spring:
  application:
    name: spring-cloud-kafka-8086
  cloud:
    stream:
      default-binder: kafka   #指定kafka stream来作为默认消息中间件
      kafka:
        binder:
          brokers: localhost    #kafka的服务端列表
          zkNodes: localhost    #kafka服务端连接的zookeeper节点列表
          headers: myType       #传递自定义header信息
          configuration:
            auto:
              offset:
                reset: latest   #可以设置原生kafka属性

server:
  port: 8086

eureka:
  client:
    serviceUrl:
     defaultZone: http://localhost:8080/eureka/


management:
  security:
    enabled: false

