spring:
  profiles:
    active: dev
  application:
    name: organization-service-8100
  zipkin:
    base-url: http://localhost:8087



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

server:
  port: 8100

feign:
  hystrix:
    enabled: true

mybatis:
  type-aliases-package: com.eztcn.api.bean
  mapper-locations: classpath:com/eztcn/organization/mapper/*Mapper.xml





