spring:
  application:
    name: spring-cloud-config-8082
  cloud:
    config:
      server:
        git:
          uri: https://git.oschina.net/eztcncom/server-config.git
          search-paths: /
          username: dev@eztcn.com
          password: Ezt20170301


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

server:
  port: 8082


management:
  security:
    enabled: false