spring:
  application:
    name: spring-cloud-eureka-server-8080

server:
  port: 8080

eureka:
  server:
    enable-self-preservation: false             # 关闭自我保护模式（缺省为打开）
    eviction-interval-timer-in-ms: 1000         # 续期时间，即扫描失效服务的间隔时间（缺省为60*1000ms）
  instance:
    prefer-ip-address: true                     # 设置微服务调用地址为IP优先（缺省为false）
    lease-renewal-interval-in-seconds: 5        # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 15    # 发呆时间，即服务续约到期时间（缺省为90s）
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/